version: "3.3"
services:
  product-service:
    build: ./products
  website:
    image: php:apache
    volumes:
      - .website:/var/www/html
    ports:
      - 85:80
    depends_on: 
      - product-service
